server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: goalxuan
      max-active: 20
      max-wait: 6000
      min-idle: 1
      test-on-borrow: true
      test-on-return: true
  mvc:
    static-path-pattern: /static/**

logging:
  level:
    com.neuedu.dao: debug

mybatis:
  mapper-locations: classpath*:com/example/demo/mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql

redis:
  max:
    total: 8
    idle: 8
  min:
    idle: 2
  test:
    borrow: true
    return: true
  ip: 47.95.119.164
  port: 5379
  password: Qinfo20180507@
  timeout: 2000