package com.example.demo.dao;

import com.example.demo.pojo.Administrator;
import java.util.List;

public interface AdministratorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_administrator
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_administrator
     *
     * @mbg.generated
     */
    int insert(Administrator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_administrator
     *
     * @mbg.generated
     */
    Administrator selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_administrator
     *
     * @mbg.generated
     */
    List<Administrator> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_administrator
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Administrator record);
}